=== jswordfish/v2crm/src/main/resources/templates/template_schema_v1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="template">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element ref="addresses"/>
        <xs:element ref="entities"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="addresses">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="address" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="address">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="line" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="entities">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="entity" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="entity">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="textAsPresent" type="xs:string"/>
        <xs:element name="outputText" type="xs:string"/>
        <xs:element name="xCoordinate" type="xs:string"/>
        <xs:element name="yCoordinate" type="xs:string"/>
        <xs:element name="dataType" type="xs:string"/>
        <xs:element name="beforeText" type="xs:string"/>
        <xs:element name="afterText" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jswordfish/v2crm/src/main/resources/templates/template_verizon.xml
<?xml version="1.0" encoding="UTF-8"?>
  <template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="template_schema_v1.xsd">
     <name>Verizon Wireless</name>
      <addresses>
        <address>
          <line>PO BOX 4005</line>
          <line>ACWORTH, GA 30101-9006</line>
        </address>
        <address>
          <line>PO BOX 4005 ACWORTH, GA 30101-9006</line>
        </address>
    </addresses>
     <entities>
      <entity>
          <textAsPresent>Account Number</textAsPresent>
          <outputText>ACCOUNT_NUMBER</outputText>
          <xCoordinate>na</xCoordinate>
          <yCoordinate>565.9199829101562</yCoordinate>
          <dataType>longWithHash</dataType>
          <beforeText>Account Number</beforeText>
          <afterText></afterText>
      </entity>   
      <entity>
          <textAsPresent>Total Current Charges</textAsPresent>
          <outputText>DUE_AMT</outputText>
          <xCoordinate>na</xCoordinate>
          <yCoordinate>257.280029296875</yCoordinate>
          <dataType>floatWithCurrency</dataType>
          <beforeText>Total Current Charges</beforeText>
          <afterText></afterText>
         </entity> 
      <entity>
          <textAsPresent>Invoice Number</textAsPresent>
          <outputText>INVOICE_NUMBER</outputText>
          <xCoordinate>na</xCoordinate>
          <yCoordinate>577.4400024414062</yCoordinate>
          <dataType>long</dataType>
          <beforeText>Invoice Number</beforeText>
          <afterText></afterText>
      </entity>
      <entity>
          <textAsPresent>Bill Date</textAsPresent>
          <outputText>BILL_DATE</outputText>
          <xCoordinate>na</xCoordinate>
          <yCoordinate>554.3999633789062</yCoordinate>
           <dataType>date</dataType>
           <beforeText>Bill Date</beforeText>
          <afterText></afterText>
      </entity>
      <!-- <entity>
          <textAsPresent>Due Date</textAsPresent>
          <outputText>DUE_DATE</outputText>
          <xCoordinate>na</xCoordinate>
          <yCoordinate>603.5999755859375</yCoordinate>
           <dataType>date</dataType>
           <beforeText>Total Amount Due by</beforeText>
          <afterText></afterText>
      </entity> -->
     </entities>
</template>

=== jswordfish/v2crm/src/main/resources/templates/template_expressToll.xml
<?xml version="1.0" encoding="UTF-8"?>
  <template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="template_schema_v1.xsd">
     <name>EXpressToll</name>
      <addresses>
        <address>
          <line>22470 E. 6th Parkway, Suite 110</line>
          <line>Aurora, CO 80018</line>
        </address>
     </addresses>
     <entities>
         
      <entity>
          <textAsPresent>Remaining Balance</textAsPresent>
          <outputText>DUE_AMT </outputText>
          <xCoordinate>na</xCoordinate>
          <yCoordinate>179.91802978515625</yCoordinate>
          <dataType>floatWithCurrency</dataType>
          <beforeText>Remaining Balance :</beforeText>
          <afterText></afterText>
         </entity> 
      <entity>
          <textAsPresent>Payments Made</textAsPresent>
          <outputText>PAYMENTS_MADE</outputText>
          <xCoordinate>na</xCoordinate>
          <yCoordinate>129.78802490234375</yCoordinate>
          <dataType>long</dataType>
          <beforeText>Payments Made :</beforeText>
          <afterText></afterText>
      </entity>
    </entities>
</template>

=== jswordfish/v2crm/src/main/resources/templates/template_comcast.xml
<?xml version="1.0" encoding="UTF-8"?>
  <template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="template_schema_v1.xsd">
          <name>Comcast Cable</name>
   <addresses>
   	  <address>
        <line>PO BOX 34744</line>
        <line>SEATTLE WA   98124-1744</line>      
      </address>
      <address>
        <line>8497 2000  NO RP 09 09102012 NNNNNNNN 01 999259</line>      
      </address>
   </addresses>
     <entities>
      <entity>
          <textAsPresent>Account Number</textAsPresent>
          <outputText>ACCOUNT_NUMBER</outputText>
          <xCoordinate>na</xCoordinate>
          <yCoordinate>40.29998779296875</yCoordinate>
          <dataType>longWithSpace</dataType>
          <beforeText>Account Number</beforeText>
          <afterText></afterText>
      </entity>   
      <entity>
          <textAsPresent>Total Amount Due</textAsPresent>
          <outputText>DUE_AMT</outputText>
          <xCoordinate>na</xCoordinate>
          <yCoordinate>62.4000244140625</yCoordinate>
          <dataType>floatWithCurrency</dataType>
          <beforeText>Total Amount Due</beforeText>
          <afterText></afterText>
         </entity> 
      <entity>
          <textAsPresent>Billing Date</textAsPresent>
          <outputText>BILLING_DATE</outputText>
          <xCoordinate>na</xCoordinate>
          <yCoordinate>51.3499755859375</yCoordinate>
          <dataType>date</dataType>
          <beforeText>Billing Date</beforeText>
          <afterText></afterText>
      </entity>
      <entity>
          <textAsPresent>Payment Due By</textAsPresent>
          <outputText>PAYMENT_DUE_BY</outputText>
          <xCoordinate>na</xCoordinate>
          <yCoordinate>73.4000244140625</yCoordinate>
           <dataType>date</dataType>
           <beforeText>Payment Due By</beforeText>
          <afterText></afterText>
      </entity>
     </entities>
</template>
